#!/bin/bash

PEGASO_START_SCRIPT_PWD=$(pwd)

# this is a code snipped:
# from http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
# to understand what directory it's stored in bash script itself

PEGASO_SOURCE="${BASH_SOURCE[0]}"
while [ -h "$PEGASO_SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  PEGASO_DIR="$( cd -P "$( dirname "$PEGASO_SOURCE" )" && pwd )"
  PEGASO_SOURCE="$(readlink "$PEGASO_SOURCE")"
  [[ $PEGASO_SOURCE != /* ]] && PEGASO_SOURCE="$PEGASO_DIR/$PEGASO_SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
PEGASO_SCRIPT_DIR="$( cd -P "$( dirname "$PEGASO_SOURCE" )" && pwd )"
PEGASO_SCRIPT_FILE=$(basename "$PEGASO_SOURCE")
# end of snipped

orig="$(pwd)"

cd "$PEGASO_SCRIPT_DIR"
cd .. || exit 1
export PEGASO_ROOT="$(pwd)"

# PEGASO_PARENT_ROOT="$(dirname "$PEGASO_ROOT")"
# echo "$PEGASO_ROOT"
# echo "$PEGASO_PARENT_ROOT"

function syntax() {
	cat <<EOF
 $PEGASO_SCRIPT_FILE 
 
 remove-unversioned-all    | svn cleanup --remove-unversioned --remove-ignored
 checkout-smart <BASEREPO> | get trunk,tags,branch but only trunk as infinity
 status-egrep <STATUS-LETTER-EGREP-FILTER> <optiona-status-args> 
                           | filter 'status' output based on status letter 
EOF
}


cmd="$1"
shift
cd "$orig" || exit 2

case "$cmd" in
	remove-unversioned-all)
	    svn cleanup --remove-unversioned --remove-ignored
	    ;;
	checkout-smart)
	    svn co --depth immediates $*
	    ;;
	status-egrep)
	    GREP_OPT="$1"
	    if [ -z "$GREP_OPT" ]; then
		    echo "missed option"
		    syntax
	    fi
	    OTHER_OPS="$2"
	    svn status $OTHER_OPS | egrep "$GREP_OPT" | awk -- '{print $2}'
	    ;;	
	*)
		echo "unknown param $cmd"
		syntax
		;;
esac

